Implement pipeline requirement on github reviews
BonnyCI/zuul pull request #14
Opened 2017-01-31 22:54 UTC by j2sol

This shoves github reviews into the data model of gerrit approvals, so
that zuul can require them for pipeline. Users with push access provide
a 2/-2, others provide 1/-1.

Brings in an unreleased Github3.py code. Further extends that code to
determine if a user has push rights to a repository.

Closes BonnyCI/projman#74

Change-Id: I3ab2139c2b11b7dc8aa896a03047615bcf42adba
Signed-off-by: Jesse Keating <omgjlk@us.ibm.com>

2017-01-31 23:33 UTC, ConsoleCatzirl approved these changes
Looks good

2017-02-03 00:06 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/14/1486079429.2/tox_py27 : FAILURE in 16m 07s

2017-02-03 00:17 UTC, rattboi requested changes

2017-02-03 00:17 UTC, rattboi commented on tests/test_github_requirements.py
> +>>>>>>> Implement pipeline requirement on github reviews
This here is gonna be a problem...

2017-02-03 00:19 UTC, j2sol commented on tests/test_github_requirements.py
> +>>>>>>> Implement pipeline requirement on github reviews
Fixed!  thanks.

2017-02-03 00:39 UTC, rattboi approved these changes

2017-02-03 00:41 UTC, merged