Fixup integration handling
BonnyCI/zuul pull request #25
Opened 2017-02-15 12:50 UTC by jamielennox

Installation_id is not a one off configurable option that can be stored.
Luckily it's available in webhook events that are sent through the
integration. Getting this passed through zuul and back as an event is
going to be difficult, however the same project always has the same
installation_id so if we just save this when a webhook is received we
can fetch it again later.

Change-Id: I917e09d79a4eca3172ee86321a437fe3fe0eb424
Signed-off-by: Jamie Lennox <jamielennox@gmail.com>

2017-02-15 12:51 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/25/1487163059.01/tox_py27 : POST_FAILURE in 12s

2017-02-15 21:12 UTC, jamielennox commented
recheck

2017-02-15 21:29 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/25/1487193167.65/tox_py27 : FAILURE in 16m 21s

2017-02-15 22:46 UTC, omgjlk requested changes
There's a lot of churn here, and it's pretty hard to review it correctly, so relying on the tests a bit, and we'll probably have to iterate a bit on it as it gets deployed into prod. Tests are failing though, I left an in-line comment where things went awry.

2017-02-15 22:46 UTC, j2sol commented on zuul/connection/github.py
> +        return 'https://%s/%s' % (self.git_host, project.name)
Might need to make these `project.get('name')`, since in the test data this is a plain dict, and not a github3.py object.

2017-02-28 18:53 UTC, jesusaurus commented on zuul/connection/github.py
> -        else:
Why are we removing the else level? If we login with the api_token, don't we want to skip the integration stuff?

2017-03-06 03:34 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/25/1488770138.52/tox_py27 : FAILURE in 18m 20s

2017-03-06 07:18 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/zuul/25/1488783586.87/tox_py27 : FAILURE in 18m 14s

2017-03-11 01:15 UTC, rattboi commented
recheck

2017-03-11 01:15 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2017-03-11 01:30 UTC, rattboi commented
recheck

2017-03-11 01:30 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2017-03-26 23:10 UTC, jamielennox commented
Think i've got all of this merged in more manageable pieces now.

2017-03-26 23:10 UTC, closed without merging